### PR TITLE
Optionally use certifi SSL certificates

### PR DESCRIPTION
**Pull request by Dobatymo**
Often there can be issues with the OS builtin SSL certificates. The `certifi` libary provides its own set of certificates and it's commonly used by other Python HTTP libraries. I added a flag `--certifi` to allow mtv-dl to use these certificates.

### CODE REVIEW

**Comment by fnep** [comment]
Wow, thank you for this pull request! Would you please add the dependency also to the requirements.txt?

**Comment by Dobatymo** [comment]
Hi, I added it to the requirements file. I also added typing-extensions which is used by the code and also in the pyproject file.

**Comment by fnep** [comment]
Perfect, thank you for cleaning up the mismatch.

**Comment by fnep** [comment]
The changes are now released as v0.19 on pypi.

**Pull request merged**
